'use strict';
// Erweiterungen: Skriptothek, Unterrichtszuordnungen, Auswertung, OneDrive-Ordner.
const extraState=()=>{state.library=state.library||[];state.unitLinks=state.unitLinks||{};return state};
const safeFolder=s=>String(s||'Unbenannt').replace(/[\\/:*?"<>|#%]/g,'_').trim().slice(0,95);
const esc=escapeHtml;
const htmlBtn=(label,id)=>`<button class="btn secondary" id="${id}">${label}</button>`;
async function ensurePath(token,parts){let folder=await appRoot(token);for(const p of parts)folder=await ensureChildFolder(token,folder.id,safeFolder(p));return folder}
async function ensureFolderTree(interactive=false){if(!navigator.onLine)return false;const token=await getGraphToken(interactive);const year=currentYear()?.label||'Schuljahr';await ensurePath(token,['Schuljahre',year]);await ensurePath(token,['Skriptothek']);await ensurePath(token,['Auswertungen']);for(const c of state.classes.filter(x=>x.yearId===state.activeYear)){const base=['Schuljahre',year,c.code];await ensurePath(token,[...base,'Skripten']);await ensurePath(token,[...base,'Auswertungen']);await ensurePath(token,[...base,'Unterrichtseinheiten']);for(const u of classUnits(c.id))await ensurePath(token,[...base,'Unterrichtseinheiten',`${u.date}_${u.id.slice(-6)}`]);for(const g of c.groups){await ensurePath(token,[...base,'Gruppen',g.name]);for(const s of groupStudents(c.id,g.id)){const root=[...base,'Gruppen',g.name,`${s.name}_${s.id.slice(-6)}`];await ensurePath(token,root);await ensurePath(token,[...root,'Arbeiten']);await ensurePath(token,[...root,'Auswertungen']);await ensurePath(token,[...root,'Unterlagen'])}}}return true}
let folderTimer=0,folderBusy=false,lastFolderSignature="";
function folderSignature(){return JSON.stringify([state.activeYear,state.classes.map(c=>[c.id,c.code,c.groups.map(g=>[g.id,g.name])]),state.students.map(s=>[s.id,s.name,s.classId,s.groupId]),state.units.map(u=>[u.id,u.date,u.classId])])}
function queueFolderSync(){clearTimeout(folderTimer);folderTimer=setTimeout(async()=>{if(folderBusy||syncBusy||!navigator.onLine)return;const signature=folderSignature();if(signature===lastFolderSignature)return;folderBusy=true;try{await ensureFolderTree(false);lastFolderSignature=signature}catch(e){console.info('OneDrive Ordner später anlegen:',e.message)}finally{folderBusy=false}},3000)}
const baseSave=saveState;saveState=function(){baseSave();queueFolderSync()};
const basePush=syncPush;syncPush=async function(o){const ok=await basePush(o);if(ok)try{await ensureFolderTree(false);lastFolderSignature=folderSignature()}catch(e){alert('Daten gespeichert, aber Ordneranlage noch nicht vollständig: '+e.message)}return ok};
const basePull=syncPull;syncPull=async function(o){const ok=await basePull(o);if(ok)extraState();return ok};
const baseRender=render;render=function(){baseRender();if(route.type==='dashboard'){const head=view.querySelector('.view-header .toolbar')||view.querySelector('.view-header');if(head){const box=document.createElement('div');box.className='toolbar';box.innerHTML=htmlBtn('Skriptothek','extraLibrary')+htmlBtn('Auswertung / PDF','extraReport')+htmlBtn('OneDrive-Ordner anlegen','extraFolders');head.append(box);box.querySelector('#extraLibrary').onclick=renderLibrary;box.querySelector('#extraReport').onclick=()=>renderReport();box.querySelector('#extraFolders').onclick=async()=>{try{await ensureFolderTree(true);alert('Ordnerstruktur in OneDrive erstellt.')}catch(e){alert('Ordneranlage fehlgeschlagen: '+e.message)}}}}if(route.type==='class'){const c=cls(route.classId);const u=state.units.find(x=>x.id===route.unitId)||currentUnit(c.id);const head=view.querySelector('.view-header .toolbar');if(head&&u){const b=document.createElement('button');b.className='btn secondary';b.textContent='Skripten / Seiten';b.onclick=()=>unitScripts(c.id,u.id);head.append(b)}if(head){const b=document.createElement('button');b.className='btn secondary';b.textContent='Auswertung';b.onclick=()=>renderReport(c.id);head.append(b)}}if(route.type==='student'){const head=view.querySelector('.view-header .toolbar');if(head){const b=document.createElement('button');b.className='btn secondary';b.textContent='Schülerbericht / PDF';b.onclick=()=>renderReport(cls(student(route.studentId).classId).id,null,route.studentId);head.append(b)}}};
async function uploadFileToLibrary(file){if(!file||!(/\.pdf$/i.test(file.name)||/^image\//.test(file.type)))throw new Error('Nur PDF oder Bilder erlaubt');if(file.size>40*1024*1024)throw new Error('Maximal 40 MB pro Datei');const token=await getGraphToken(true);const folder=await ensurePath(token,['Skriptothek']);const name=`${uid('doc')}_${safeFolder(file.name)}`;const r=await fetch(`https://graph.microsoft.com/v1.0/me/drive/items/${folder.id}:/${encodeURIComponent(name)}:/content`,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':file.type||'application/octet-stream'},body:file});if(!r.ok)throw new Error('Upload '+r.status+': '+await r.text());const meta=await r.json();extraState().library.push({id:uid('lib'),name:file.name,driveId:meta.id,mime:file.type||'',size:file.size,notes:'',createdAt:new Date().toISOString()});saveState();return meta}
async function openLibraryFile(item){try{const token=await getGraphToken(true);const r=await graph(token,`/me/drive/items/${item.driveId}`);if(r.webUrl)window.open(r.webUrl,'_blank','noopener');else alert('Kein Link zur Datei verfügbar')}catch(e){alert('Datei öffnen fehlgeschlagen: '+e.message)}}
function renderLibrary(){extraState();view.innerHTML=`<div class="view-header"><div><h2>Skriptothek</h2><div class="sub">Originaldateien einmalig im OneDrive-App-Ordner; Seitenbereiche je Einheit verlinken.</div></div><div class="toolbar">${htmlBtn('Zur Übersicht','libBack')}<button class="btn" id="libUpload">+ PDF / Bild</button></div></div><div class="section-card">${state.library.length?state.library.map(i=>`<div class="schedule-block"><div><b>${esc(i.name)}</b><div class="small">${Math.round(i.size/1024)} KB · ${esc(i.mime)}</div></div><div class="toolbar"><button class="btn secondary" data-open="${i.id}">Öffnen</button><button class="btn secondary" data-note="${i.id}">Notiz</button></div></div>`).join(''):'Noch keine Unterlagen vorhanden.'}</div><input type="file" id="libraryPicker" accept=".pdf,image/*" hidden>`;document.getElementById('libBack').onclick=()=>{route={type:'dashboard'};render()};document.getElementById('libUpload').onclick=()=>document.getElementById('libraryPicker').click();document.getElementById('libraryPicker').onchange=async e=>{try{await uploadFileToLibrary(e.target.files[0]);renderLibrary()}catch(x){alert(x.message)}};view.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openLibraryFile(state.library.find(x=>x.id===b.dataset.open)));view.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{const i=state.library.find(x=>x.id===b.dataset.note);const v=prompt('Notiz zum Skript',i.notes||'');if(v!==null){i.notes=v;saveState();renderLibrary()}})}
function unitScripts(cid,unitId){extraState();const u=state.units.find(x=>x.id===unitId),links=state.unitLinks[unitId]||[];openModal(`<h2>Skripten · ${esc(fmtDate(u.date))}</h2><p>${esc(u.topic)}</p><div class="section-card">${links.map((l,n)=>{const d=state.library.find(x=>x.id===l.docId);return `<div class="schedule-block"><div><b>${esc(d?.name||'Datei fehlt')}</b><div>Seiten: ${esc(l.pages||'gesamtes Dokument')}</div><div>${esc(l.notes||'')}</div></div><div class="toolbar"><button class="btn secondary" data-doc="${n}">Öffnen</button><button class="btn danger" data-remove="${n}">Entfernen</button></div></div>`}).join('')||'Noch keine Zuordnung'}</div><div class="field"><label>Skript auswählen</label><select id="scriptDoc">${state.library.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>Seiten (z. B. 7 oder 3,7-9,24)</label><input id="scriptPages" placeholder="7-9"></div><div class="field"><label>Notizen zur Seitenzuordnung</label><textarea id="scriptNotes"></textarea></div><div class="modal-actions"><button class="btn secondary" id="scriptLibrary">Skriptothek öffnen</button><button class="btn" id="scriptAdd">Zuordnen</button></div>`);document.getElementById('scriptAdd').onclick=()=>{const docId=document.getElementById('scriptDoc').value,pages=document.getElementById('scriptPages').value.trim(),notes=document.getElementById('scriptNotes').value;if(!docId)return alert('Bitte zuerst ein Skript hochladen.');if(pages&&!/^\d+(\s*(-\s*\d+)?\s*,\s*\d+(\s*-\s*\d+)?)*$/.test(pages))return alert('Seiten als 7 oder 3,7-9,24 eingeben.');state.unitLinks[unitId]=[...links,{docId,pages,notes}];saveState();unitScripts(cid,unitId)};document.getElementById('scriptLibrary').onclick=()=>{closeModal();renderLibrary()};modal.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{links.splice(Number(b.dataset.remove),1);state.unitLinks[unitId]=links;saveState();unitScripts(cid,unitId)});modal.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>{const l=links[Number(b.dataset.doc)],d=state.library.find(x=>x.id===l.docId);if(d)openLibraryFile(d)})}
function reportData(cid,gid,sid){const classes=state.classes.filter(c=>c.yearId===state.activeYear&&(!cid||c.id===cid));const students=state.students.filter(s=>classes.some(c=>c.id===s.classId)&&(!gid||s.groupId===gid)&&(!sid||s.id===sid));return{classes,students}}
function classWeights(cid){state.reportWeights ||= {};if(!state.reportWeights[cid])state.reportWeights[cid]=Object.fromEntries(RUBRICS.map(r=>[r,100/RUBRICS.length]));const w=state.reportWeights[cid];const vals=RUBRICS.map(k=>Number(w[k])||0);if(vals.every(v=>v<=2)&&vals.reduce((a,b)=>a+b,0)<=RUBRICS.length*2){const total=vals.reduce((a,b)=>a+b,0)||1;RUBRICS.forEach(k=>w[k]=Math.round((Number(w[k])||0)/total*10000)/100)}return w}
function scoreDetail(r,weights){if(!r)return null;let sum=0,den=0,raw=0,count=0;for(const k of RUBRICS){const v=Number(r.ratings?.[k]),w=Math.max(0,Number(weights[k])||0);if(r.ratings?.[k]!==undefined&&r.ratings?.[k]!==null&&r.ratings?.[k]!==''&&Number.isFinite(v)){raw+=v;count++;if(w){sum+=v*w;den+=w}}}return count?{points:raw,weightedPoints:sum,weightSum:den,average:den?sum/den:null,count}:null}
function renderReport(cid='',gid='',sid=''){
 const origin=typeof route==='object'?{...route}:{type:'dashboard'};
 const classes=state.classes.filter(c=>c.yearId===state.activeYear);
 let excluded=new Set();
 view.innerHTML=`<div class="view-header"><div><h2>Gesamtauswertung / PDF</h2><div class="sub">Gruppen- und Schülerstatistik · alle ausgewählten Unterrichtseinheiten</div></div><div class="toolbar">${htmlBtn('Zurück','reportBack')}<button class="btn" id="reportPrint">Drucken / PDF</button></div></div>
 <div class="section-card report-settings"><div class="form-grid"><div class="field"><label>Klasse</label><select id="reportClass"><option value="">Alle Klassen</option>${classes.map(c=>`<option value="${c.id}" ${c.id===cid?'selected':''}>${esc(c.code)}</option>`).join('')}</select></div><div class="field"><label>Gruppe</label><select id="reportGroup"></select></div><div class="field"><label>Schüler</label><select id="reportStudent"></select></div>
 <div class="field"><label>Papier</label><select id="reportPaper"><option>A4</option><option>A3</option></select></div><div class="field"><label>Ausrichtung</label><select id="reportOrientation"><option value="portrait">Hochformat</option><option value="landscape">Querformat</option></select></div><div class="field"><label>Seitenanpassung</label><select id="reportFit"><option value="width">An Seitenbreite</option><option value="height">An Seitenhöhe</option></select></div></div>
 <label class="inline-check"><input id="reportNotes" type="checkbox"> Notizen anzeigen</label> <label class="inline-check"><input id="reportShowWeights" type="checkbox"> Gewichtungen im Bericht anzeigen</label></div>
 <div class="section-card report-settings" id="reportWeightPanel"></div>
 <div class="section-card report-settings"><h3>Unterrichtseinheiten</h3><div class="toolbar"><button class="btn secondary" id="reportAllUnits">Alle auswählen</button><button class="btn secondary" id="reportNoUnits">Alle abwählen</button></div><div id="reportUnits" class="report-unit-list"></div></div><div id="reportBody"></div>`;
 const sc=document.getElementById('reportClass'),sg=document.getElementById('reportGroup'),ss=document.getElementById('reportStudent'),ul=document.getElementById('reportUnits');
 document.getElementById('reportBack').onclick=()=>{route=origin;render()};
 const units=()=>classes.filter(c=>!sc.value||c.id===sc.value).flatMap(c=>classUnits(c.id).map(u=>({...u,classCode:c.code}))).sort((a,b)=>a.date.localeCompare(b.date));
 function selectedUnits(s){return classUnits(s.classId).filter(u=>!excluded.has(u.id))}
 function unitUI(){ul.innerHTML=units().map(u=>`<label class="report-unit"><input type="checkbox" data-report-unit="${u.id}" ${excluded.has(u.id)?'':'checked'}> ${esc(u.classCode)} · ${esc(fmtDate(u.date))} · ${esc(u.topic||'Ohne Thema')}</label>`).join('')||'Keine Einheiten vorhanden.';ul.querySelectorAll('[data-report-unit]').forEach(el=>el.onchange=()=>{el.checked?excluded.delete(el.dataset.reportUnit):excluded.add(el.dataset.reportUnit);draw()})}
 function weightsUI(){const c=cls(sc.value),panel=document.getElementById('reportWeightPanel');if(!c){panel.innerHTML='<h3>Kategoriegewichtung</h3><p>Eine Klasse auswählen, um deren Gewichtungen zu bearbeiten.</p>';return}const weights=classWeights(c.id);panel.innerHTML=`<h3>Gewichtung · ${esc(c.code)}</h3><p id="weightTotal" class="sub"></p><p class="sub">Gewichtung in Prozent. Summe aller Kategorien muss 100 % ergeben. Fehlende Bewertungen zählen nicht als 0 Punkte.</p><div class="report-weight-grid">${RUBRICS.map(k=>`<label>${esc(k)} <input type="number" min="0" max="100" step="1" data-weight="${esc(k)}" value="${Number(weights[k])||0}"> %</label>`).join('')}</div>`;document.getElementById('weightTotal').textContent='Summe: '+RUBRICS.reduce((a,k)=>a+(Number(weights[k])||0),0).toLocaleString('de-AT')+' %';panel.querySelectorAll('[data-weight]').forEach(el=>el.onchange=()=>{weights[el.dataset.weight]=Math.min(100,Math.max(0,Number(el.value)||0));const total=RUBRICS.reduce((a,k)=>a+(Number(weights[k])||0),0);document.getElementById('weightTotal').textContent='Summe: '+total.toLocaleString('de-AT')+' %'+(Math.abs(total-100)>.01?' – bitte auf 100 % korrigieren':'');saveState();draw()})}
 function fill(){const c=cls(sc.value);sg.innerHTML='<option value="">Alle Gruppen</option>'+(c?.groups||[]).map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');if(gid&&c?.groups.some(g=>g.id===gid)){sg.value=gid;gid=''}weightsUI();fillStudents();unitUI();draw()}
 function fillStudents(){const arr=state.students.filter(s=>(!sc.value||s.classId===sc.value)&&(!sg.value||s.groupId===sg.value));ss.innerHTML='<option value="">Alle Schüler</option>'+arr.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');if(sid&&arr.some(s=>s.id===sid)){ss.value=sid;sid=''}draw()}
 const fmt=n=>n==null||!Number.isFinite(n)?'–':n.toFixed(2).replace('.',',');
 function draw(){const {students}=reportData(sc.value,sg.value,ss.value),showWeights=document.getElementById('reportShowWeights').checked,notes=document.getElementById('reportNotes').checked;
 const details=students.map(s=>{const c=cls(s.classId),weights=classWeights(c.id),rows=selectedUnits(s).map(u=>({u,r:getRecord(s.id,u.id,false),d:scoreDetail(getRecord(s.id,u.id,false),weights)}));const assessed=rows.filter(x=>x.d&&x.d.average!=null),sumPoints=rows.reduce((a,x)=>a+(x.d?.points||0),0),sumWeighted=assessed.reduce((a,x)=>a+x.d.weightedPoints,0),sumWeight=assessed.reduce((a,x)=>a+x.d.weightSum,0),missed=rows.reduce((a,x)=>a+calcMissedUE(c,x.r),0);return{s,c,rows,sumPoints,avg:sumWeight?sumWeighted/sumWeight:null,missed,assessed:assessed.length}});
 const groups=new Map();for(const x of details){const key=x.c.id+'|'+x.s.groupId;if(!groups.has(key))groups.set(key,{c:x.c,g:x.c.groups.find(g=>g.id===x.s.groupId),items:[]});groups.get(key).items.push(x)}
 const groupHTML=[...groups.values()].map(({c,g,items})=>{const w=classWeights(c.id),cats=RUBRICS.map(k=>{const vals=items.flatMap(x=>x.rows.map(z=>z.r?.ratings?.[k]).filter(v=>v!==undefined&&v!==null&&v!==''&&Number.isFinite(Number(v))).map(Number));return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null});const weighted=items.flatMap(x=>x.rows).reduce((acc,z)=>{if(z.d?.average!=null){acc.a+=z.d.weightedPoints;acc.b+=z.d.weightSum}return acc},{a:0,b:0});return `<div class="section-card report-page"><h3>Gruppe · ${esc(c.code)} · ${esc(g?.name||'Ohne Gruppe')}</h3><p>${items.length} Schüler · gewichteter Gruppendurchschnitt: <b>${fmt(weighted.b?weighted.a/weighted.b:null)} / 4</b></p><div class="table-wrap"><table class="report-table"><thead><tr><th>Kategorie</th><th>Ø Punkte (1–4)</th>${showWeights?'<th>Gewicht</th>':''}</tr></thead><tbody>${RUBRICS.map((k,i)=>`<tr><td>${esc(k)}</td><td>${fmt(cats[i])}</td>${showWeights?`<td>${fmt(Number(w[k])||0)} %</td>`:''}</tr>`).join('')}</tbody></table></div><div class="table-wrap"><table class="report-table"><thead><tr><th>Schüler</th><th>Gesamtpunkte</th><th>Gewichteter Ø</th><th>Fehl-UE</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.s.name)}</td><td>${x.sumPoints}</td><td>${fmt(x.avg)}</td><td>${fmt(x.missed)}</td></tr>`).join('')}</tbody></table></div></div>`}).join('');
 const studentHTML=details.map(x=>{const w=classWeights(x.c.id);return `<div class="section-card report-page"><h3>Schülerbericht · ${esc(x.s.name)}</h3><p>${esc(x.c.code)} · ${esc(x.c.groups.find(g=>g.id===x.s.groupId)?.name||'')} · ${x.rows.length} Einheiten</p><div class="table-wrap"><table class="report-table"><thead><tr><th>Datum</th><th>Einheit</th>${RUBRICS.map(k=>`<th>${esc(k)}${showWeights?` (${fmt(Number(w[k])||0)} %)`:''}</th>`).join('')}<th>Punkte</th><th>Gewichteter Ø</th><th>Fehl-UE</th></tr></thead><tbody>${x.rows.map(({u,r,d})=>`<tr><td>${esc(fmtDate(u.date))}</td><td>${esc(u.topic||'–')}</td>${RUBRICS.map(k=>`<td>${r?.ratings?.[k]??'–'}</td>`).join('')}<td>${d?.points??'–'}</td><td>${fmt(d?.average)}</td><td>${fmt(calcMissedUE(x.c,r))}</td></tr>${notes&&(r?.comment||Object.values(r?.ratingNotes||{}).some(Boolean))?`<tr><td colspan="${RUBRICS.length+5}" class="report-note">${esc(r?.comment||'')} ${Object.entries(r?.ratingNotes||{}).filter(([,v])=>v).map(([k,v])=>`${esc(k)}: ${esc(v)}`).join(' · ')}</td></tr>`:''}`).join('')}</tbody><tfoot><tr><th colspan="${RUBRICS.length+2}">Gesamt / gewichteter Durchschnitt</th><th>${x.sumPoints}</th><th>${fmt(x.avg)}</th><th>${fmt(x.missed)}</th></tr></tfoot></table></div></div>`}).join('');
 document.getElementById('reportBody').innerHTML=`<div class="report-summary"><h3>Statistik · ${esc(currentYear()?.label||'')}</h3><p>${students.length} Schüler · ${units().filter(u=>!excluded.has(u.id)).length} ausgewählte Einheiten · ${new Date().toLocaleDateString('de-AT')}</p><p class="sub">Punkte: Summe der tatsächlich vergebenen Kategoriepunkte (1–4). Gewichteter Ø: Summe (Punkte × Gewicht) / Summe der Gewichte aller vorhandenen Bewertungen. Unbewertete Felder bleiben unberücksichtigt.</p></div>${groupHTML}${studentHTML}`;
 }
 sc.onchange=()=>{gid='';sid='';fill()};sg.onchange=()=>{sid='';fillStudents()};ss.onchange=draw;document.getElementById('reportNotes').onchange=draw;document.getElementById('reportShowWeights').onchange=draw;
 document.getElementById('reportAllUnits').onclick=()=>{units().forEach(u=>excluded.delete(u.id));unitUI();draw()};document.getElementById('reportNoUnits').onclick=()=>{units().forEach(u=>excluded.add(u.id));unitUI();draw()};
 document.getElementById('reportPrint').onclick=()=>{const invalid=state.classes.filter(c=>c.yearId===state.activeYear&&(!document.getElementById('reportClass').value||c.id===document.getElementById('reportClass').value)).filter(c=>Math.abs(RUBRICS.reduce((a,k)=>a+(Number(classWeights(c.id)[k])||0),0)-100)>0.01);if(invalid.length){alert('Gewichtung muss je Klasse 100 % ergeben: '+invalid.map(c=>c.code).join(', '));return}const paper=document.getElementById('reportPaper').value,orientation=document.getElementById('reportOrientation').value,fit=document.getElementById('reportFit').value;let style=document.getElementById('dynamicReportPrint');if(!style){style=document.createElement('style');style.id='dynamicReportPrint';document.head.append(style)}style.textContent=`@page{size:${paper} ${orientation};margin:9mm}@media print{.report-page{break-inside:avoid-page}.report-table{font-size:${fit==='height'?'8':'9'}pt}.report-page .table-wrap{overflow:visible}.report-page table{width:100%;max-width:100%;table-layout:fixed;overflow-wrap:anywhere}.report-page{max-width:100%;box-sizing:border-box}.report-page .table-wrap{width:100%;max-width:100%}${fit==='height'?'.report-page{font-size:9pt;padding:6px!important}':''}}`;window.print()};fill();
}
