'use strict';
// Erweiterungen: Skriptothek, Unterrichtszuordnungen, Auswertung, OneDrive-Ordner.
const extraState=()=>{state.library=state.library||[];state.unitLinks=state.unitLinks||{};return state};
const safeFolder=s=>String(s||'Unbenannt').replace(/[\\/:*?"<>|#%]/g,'_').trim().slice(0,95);
const esc=escapeHtml;
const htmlBtn=(label,id)=>`<button class="btn secondary" id="${id}">${label}</button>`;
async function ensurePath(token,parts){let folder=await appRoot(token);for(const p of parts)folder=await ensureChildFolder(token,folder.id,safeFolder(p));return folder}
async function ensureFolderTree(interactive=false){if(!navigator.onLine)return false;const token=await getGraphToken(interactive);const year=currentYear()?.label||'Schuljahr';await ensurePath(token,['Schuljahre',year]);await ensurePath(token,['Skriptothek']);await ensurePath(token,['Auswertungen']);for(const c of state.classes.filter(x=>x.yearId===state.activeYear)){const base=['Schuljahre',year,c.code];await ensurePath(token,[...base,'Skripten']);await ensurePath(token,[...base,'Auswertungen']);await ensurePath(token,[...base,'Unterrichtseinheiten']);for(const u of classUnits(c.id))await ensurePath(token,[...base,'Unterrichtseinheiten',`${u.date}_${u.id.slice(-6)}`]);for(const g of c.groups){await ensurePath(token,[...base,'Gruppen',g.name]);for(const s of groupStudents(c.id,g.id)){const root=[...base,'Gruppen',g.name,`${s.name}_${s.id.slice(-6)}`];await ensurePath(token,root);await ensurePath(token,[...root,'Arbeiten']);await ensurePath(token,[...root,'Auswertungen']);await ensurePath(token,[...root,'Unterlagen'])}}}return true}
let folderTimer=0,folderBusy=false,lastFolderSignature="";
function folderSignature(){return JSON.stringify([state.activeYear,state.classes.map(c=>[c.id,c.code,c.groups.map(g=>[g.id,g.name])]),state.students.map(s=>[s.id,s.name,s.classId,s.groupId]),state.units.map(u=>[u.id,u.date,u.classId])])}
function queueFolderSync(){clearTimeout(folderTimer);folderTimer=setTimeout(async()=>{if(folderBusy||syncBusy||!navigator.onLine)return;const signature=folderSignature();if(signature===lastFolderSignature)return;folderBusy=true;try{await ensureFolderTree(false);lastFolderSignature=signature}catch(e){console.info('OneDrive Ordner später anlegen:',e.message)}finally{folderBusy=false}},3000)}
const baseSave=saveState;saveState=function(){baseSave();queueFolderSync()};
const basePush=syncPush;syncPush=async function(o){const ok=await basePush(o);if(ok)try{await ensureFolderTree(false);lastFolderSignature=folderSignature()}catch(e){alert('Daten gespeichert, aber Ordneranlage noch nicht vollständig: '+e.message)}return ok};
const basePull=syncPull;syncPull=async function(o){const ok=await basePull(o);if(ok)extraState();return ok};
const baseRender=render;render=function(){baseRender();if(route.type==='dashboard'){const head=view.querySelector('.view-header .toolbar')||view.querySelector('.view-header');if(head){const box=document.createElement('div');box.className='toolbar';box.innerHTML=htmlBtn('Skriptothek','extraLibrary')+htmlBtn('Auswertung / PDF','extraReport')+htmlBtn('OneDrive-Ordner anlegen','extraFolders');head.append(box);box.querySelector('#extraLibrary').onclick=renderLibrary;box.querySelector('#extraReport').onclick=()=>renderReport();box.querySelector('#extraFolders').onclick=async()=>{try{await ensureFolderTree(true);alert('Ordnerstruktur in OneDrive erstellt.')}catch(e){alert('Ordneranlage fehlgeschlagen: '+e.message)}}}}if(route.type==='class'){const c=cls(route.classId);const u=state.units.find(x=>x.id===route.unitId)||currentUnit(c.id);const head=view.querySelector('.view-header .toolbar');if(head&&u){const b=document.createElement('button');b.className='btn secondary';b.textContent='Skripten / Seiten';b.onclick=()=>unitScripts(c.id,u.id);head.append(b)}if(head){const b=document.createElement('button');b.className='btn secondary';b.textContent='Auswertung';b.onclick=()=>renderReport(c.id);head.append(b)}}if(route.type==='student'){const head=view.querySelector('.view-header .toolbar');if(head){const b=document.createElement('button');b.className='btn secondary';b.textContent='Schülerbericht / PDF';b.onclick=()=>renderReport(cls(student(route.studentId).classId).id,null,route.studentId);head.append(b)}}};
async function uploadFileToLibrary(file){if(!file||!(/\.pdf$/i.test(file.name)||/^image\//.test(file.type)))throw new Error('Nur PDF oder Bilder erlaubt');if(file.size>40*1024*1024)throw new Error('Maximal 40 MB pro Datei');const token=await getGraphToken(true);const folder=await ensurePath(token,['Skriptothek']);const name=`${uid('doc')}_${safeFolder(file.name)}`;const r=await fetch(`https://graph.microsoft.com/v1.0/me/drive/items/${folder.id}:/${encodeURIComponent(name)}:/content`,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':file.type||'application/octet-stream'},body:file});if(!r.ok)throw new Error('Upload '+r.status+': '+await r.text());const meta=await r.json();extraState().library.push({id:uid('lib'),name:file.name,driveId:meta.id,mime:file.type||'',size:file.size,notes:'',createdAt:new Date().toISOString()});saveState();return meta}
async function openLibraryFile(item){try{const token=await getGraphToken(true);const r=await graph(token,`/me/drive/items/${item.driveId}`);if(r.webUrl)window.open(r.webUrl,'_blank','noopener');else alert('Kein Link zur Datei verfügbar')}catch(e){alert('Datei öffnen fehlgeschlagen: '+e.message)}}
function renderLibrary(){extraState();view.innerHTML=`<div class="view-header"><div><h2>Skriptothek</h2><div class="sub">Originaldateien einmalig im OneDrive-App-Ordner; Seitenbereiche je Einheit verlinken.</div></div><div class="toolbar">${htmlBtn('Zur Übersicht','libBack')}<button class="btn" id="libUpload">+ PDF / Bild</button></div></div><div class="section-card">${state.library.length?state.library.map(i=>`<div class="schedule-block"><div><b>${esc(i.name)}</b><div class="small">${Math.round(i.size/1024)} KB · ${esc(i.mime)}</div></div><div class="toolbar"><button class="btn secondary" data-open="${i.id}">Öffnen</button><button class="btn secondary" data-note="${i.id}">Notiz</button></div></div>`).join(''):'Noch keine Unterlagen vorhanden.'}</div><input type="file" id="libraryPicker" accept=".pdf,image/*" hidden>`;document.getElementById('libBack').onclick=()=>{route={type:'dashboard'};render()};document.getElementById('libUpload').onclick=()=>document.getElementById('libraryPicker').click();document.getElementById('libraryPicker').onchange=async e=>{try{await uploadFileToLibrary(e.target.files[0]);renderLibrary()}catch(x){alert(x.message)}};view.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openLibraryFile(state.library.find(x=>x.id===b.dataset.open)));view.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{const i=state.library.find(x=>x.id===b.dataset.note);const v=prompt('Notiz zum Skript',i.notes||'');if(v!==null){i.notes=v;saveState();renderLibrary()}})}
function unitScripts(cid,unitId){extraState();const u=state.units.find(x=>x.id===unitId),links=state.unitLinks[unitId]||[];openModal(`<h2>Skripten · ${esc(fmtDate(u.date))}</h2><p>${esc(u.topic)}</p><div class="section-card">${links.map((l,n)=>{const d=state.library.find(x=>x.id===l.docId);return `<div class="schedule-block"><div><b>${esc(d?.name||'Datei fehlt')}</b><div>Seiten: ${esc(l.pages||'gesamtes Dokument')}</div><div>${esc(l.notes||'')}</div></div><div class="toolbar"><button class="btn secondary" data-doc="${n}">Öffnen</button><button class="btn danger" data-remove="${n}">Entfernen</button></div></div>`}).join('')||'Noch keine Zuordnung'}</div><div class="field"><label>Skript auswählen</label><select id="scriptDoc">${state.library.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>Seiten (z. B. 7 oder 3,7-9,24)</label><input id="scriptPages" placeholder="7-9"></div><div class="field"><label>Notizen zur Seitenzuordnung</label><textarea id="scriptNotes"></textarea></div><div class="modal-actions"><button class="btn secondary" id="scriptLibrary">Skriptothek öffnen</button><button class="btn" id="scriptAdd">Zuordnen</button></div>`);document.getElementById('scriptAdd').onclick=()=>{const docId=document.getElementById('scriptDoc').value,pages=document.getElementById('scriptPages').value.trim(),notes=document.getElementById('scriptNotes').value;if(!docId)return alert('Bitte zuerst ein Skript hochladen.');if(pages&&!/^\d+(\s*(-\s*\d+)?\s*,\s*\d+(\s*-\s*\d+)?)*$/.test(pages))return alert('Seiten als 7 oder 3,7-9,24 eingeben.');state.unitLinks[unitId]=[...links,{docId,pages,notes}];saveState();unitScripts(cid,unitId)};document.getElementById('scriptLibrary').onclick=()=>{closeModal();renderLibrary()};modal.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{links.splice(Number(b.dataset.remove),1);state.unitLinks[unitId]=links;saveState();unitScripts(cid,unitId)});modal.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>{const l=links[Number(b.dataset.doc)],d=state.library.find(x=>x.id===l.docId);if(d)openLibraryFile(d)})}
function reportData(cid,gid,sid){const classes=state.classes.filter(c=>c.yearId===state.activeYear&&(!cid||c.id===cid));const students=state.students.filter(s=>classes.some(c=>c.id===s.classId)&&(!gid||s.groupId===gid)&&(!sid||s.id===sid));return{classes,students}}
function renderReport(cid='',gid='',sid=''){
 const classes=state.classes.filter(c=>c.yearId===state.activeYear);
 let excluded=new Set(),previousUnits='';
 view.innerHTML=`<div class="view-header"><div><h2>Live-Auswertung / PDF</h2><div class="sub">Unterrichtseinheiten des Schuljahres · frei auswählbar</div></div><div class="toolbar">${htmlBtn('Zur Übersicht','reportBack')}<button class="btn" id="reportPrint">Als PDF drucken</button></div></div>
 <div class="section-card"><div class="form-grid"><div class="field"><label>Klasse</label><select id="reportClass"><option value="">Alle Klassen</option>${classes.map(c=>`<option value="${c.id}" ${c.id===cid?'selected':''}>${esc(c.code)}</option>`).join('')}</select></div><div class="field"><label>Gruppe</label><select id="reportGroup"></select></div><div class="field"><label>Schüler</label><select id="reportStudent"></select></div></div>
 <label><input id="reportNotes" type="checkbox" checked> Notizen im Bericht anzeigen</label></div>
 <div class="section-card"><h3>Unterrichtseinheiten für die Auswertung</h3><div class="toolbar"><button class="btn secondary" id="reportAllUnits">Alle auswählen</button><button class="btn secondary" id="reportNoUnits">Alle abwählen</button></div><div id="reportUnits" class="report-unit-list"></div></div><div id="reportBody"></div>`;
 const sc=document.getElementById('reportClass'),sg=document.getElementById('reportGroup'),ss=document.getElementById('reportStudent'),ul=document.getElementById('reportUnits');
 document.getElementById('reportBack').onclick=()=>{route={type:'dashboard'};render()};
 const units=()=>classes.filter(c=>!sc.value||c.id===sc.value).flatMap(c=>classUnits(c.id).map(u=>({...u,classCode:c.code})) ).sort((a,b)=>a.date.localeCompare(b.date));
 function unitUI(){const us=units();ul.innerHTML=us.length?us.map(u=>`<label class="report-unit"><input type="checkbox" data-report-unit="${u.id}" ${excluded.has(u.id)?'':'checked'}> ${esc(u.classCode)} · ${esc(fmtDate(u.date))} · ${esc(u.topic||'Ohne Thema')}</label>`).join(''):'Keine Einheiten vorhanden.';ul.querySelectorAll('[data-report-unit]').forEach(el=>el.onchange=()=>{if(el.checked)excluded.delete(el.dataset.reportUnit);else excluded.add(el.dataset.reportUnit);draw()})}
 function selectedUnits(s){return classUnits(s.classId).filter(u=>!excluded.has(u.id))}
 function averageFor(s){const vals=selectedUnits(s).map(u=>getRecord(s.id,u.id,false)?.ratings?.Lehrer).filter(Number.isFinite);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
 function absenceFor(s){const c=cls(s.classId);return selectedUnits(s).reduce((a,u)=>a+calcMissedUE(c,getRecord(s.id,u.id,false)),0)}
 function fill(){const c=cls(sc.value);sg.innerHTML='<option value="">Alle Gruppen</option>'+(c?.groups||[]).map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');if(gid&&c?.groups.some(g=>g.id===gid)){sg.value=gid;gid=''}fillStudents();unitUI();draw()}
 function fillStudents(){const arr=state.students.filter(s=>(!sc.value||s.classId===sc.value)&&(!sg.value||s.groupId===sg.value));ss.innerHTML='<option value="">Alle Schüler</option>'+arr.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');if(sid&&arr.some(s=>s.id===sid)){ss.value=sid;sid=''}draw()}
 function draw(){const {students}=reportData(sc.value,sg.value,ss.value),n=units().filter(u=>!excluded.has(u.id)).length;
 document.getElementById('reportBody').innerHTML=`<div class="section-card"><h3>Auswertung · ${esc(currentYear()?.label||'')}</h3><p>${students.length} Schüler · ${n} Unterrichtseinheiten berücksichtigt · Stand ${new Date().toLocaleDateString('de-AT')}</p><div class="table-wrap"><table><thead><tr><th>Klasse</th><th>Gruppe</th><th>Schüler</th><th>Ø Lehrer (1–4)</th><th>Fehl-UE</th></tr></thead><tbody>${students.map(s=>{const c=cls(s.classId),av=averageFor(s);return `<tr><td>${esc(c.code)}</td><td>${esc(c.groups.find(g=>g.id===s.groupId)?.name||'')}</td><td>${esc(s.name)}</td><td>${av==null?'–':av.toFixed(2)}</td><td>${absenceFor(s).toFixed(1)}</td></tr>`}).join('')}</tbody></table></div></div>${document.getElementById('reportNotes').checked?students.map(s=>{const entries=selectedUnits(s).map(u=>{const r=getRecord(s.id,u.id,false);if(!r)return '';const notes=Object.entries(r.ratingNotes||{}).filter(([,v])=>v).map(([k,v])=>`${esc(k)}: ${esc(v)}`).join('<br>');return notes||r.comment?`<p><b>${esc(fmtDate(u.date))} · ${esc(u.topic)}</b><br>${notes}${r.comment?'<br>'+esc(r.comment):''}</p>`:''}).filter(Boolean);return entries.length?`<div class="section-card"><h3>${esc(s.name)}</h3>${entries.join('')}</div>`:''}).join(''):''}`;
 }
 sc.onchange=()=>{gid='';sid='';fill()};sg.onchange=()=>{sid='';fillStudents()};ss.onchange=draw;document.getElementById('reportNotes').onchange=draw;
 document.getElementById('reportAllUnits').onclick=()=>{units().forEach(u=>excluded.delete(u.id));unitUI();draw()};document.getElementById('reportNoUnits').onclick=()=>{units().forEach(u=>excluded.add(u.id));unitUI();draw()};document.getElementById('reportPrint').onclick=()=>window.print();fill();
}
