/* i-i_Doku room planner v7.1: classroom layout stored with the existing state */
(function(){
const previousRender=render;
const E=escapeHtml;
function store(){state.roomPlans ||= {};return state.roomPlans}
function plan(cid){const all=store();if(!all[cid])all[cid]=createPlan(4,3);return all[cid]}
function createPlan(rows,cols){const desks=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)desks.push({id:uid('desk'),type:'single',x:12+c*27,y:26+r*16,angle:0,students:[]});return {rows,cols,desks,fixtures:[{id:'board',type:'board',x:33,y:3,angle:0},{id:'teacher',type:'teacher',x:78,y:10,angle:0},{id:'door',type:'door',x:3,y:89,angle:0},{id:'window1',type:'window',x:92,y:33,angle:0},{id:'window2',type:'window',x:92,y:61,angle:0}]}}
let edit=false,activeCid='',selectedId='',filterGroup='';
function obj(p,id){return [...p.desks,...p.fixtures].find(x=>x.id===id)}
function save(){saveState()}
function label(s){return s?E(s.name):'Frei'}
function seats(d){return d.type==='double'?2:1}
function renderRoom(cid){activeCid=cid;const c=cls(cid);if(!c)return;const p=plan(cid);const eligible=classStudents(cid).filter(s=>!filterGroup||s.groupId===filterGroup);const ids=new Set(eligible.map(s=>s.id));const used=new Set(p.desks.flatMap(d=>d.students||[]).filter(Boolean));view.innerHTML=`<div class="view-header"><div><h2>Klassenraumplan · ${E(c.code)}</h2><div class="sub">${edit?'Bearbeitungsmodus':'Unterrichtsmodus'} · ${p.desks.length} Tische · ${used.size} zugewiesene Schüler</div></div><div class="toolbar"><button class="btn secondary" id="roomBack">Zur Klasse</button><button class="btn" id="roomEdit">${edit?'Unterrichtsmodus':'Bearbeiten'}</button><button class="btn secondary" id="roomPrint">Drucken / PDF</button></div></div><div class="section-card room-tools"><label>Gruppe <select id="roomGroup"><option value="">Alle Gruppen</option>${c.groups.map(g=>`<option value="${E(g.id)}" ${filterGroup===g.id?'selected':''}>${E(g.name)}</option>`).join('')}</select></label>${edit?`<label>Reihen <input id="roomRows" type="number" min="1" max="12" value="${p.rows}" style="width:65px"></label><label>Spalten <input id="roomCols" type="number" min="1" max="10" value="${p.cols}" style="width:65px"></label><button class="btn secondary" id="roomGrid">Raster neu erstellen</button><button class="btn" id="roomAddSingle">+ Einzeltisch</button><button class="btn" id="roomAddDouble">+ Doppeltisch</button><button class="btn secondary" id="roomAddFixture">+ Raumelement</button>`:''}</div><div class="room-layout"><div class="room-canvas" id="roomCanvas">${p.fixtures.map(f=>fixtureHTML(f)).join('')}${p.desks.map(d=>deskHTML(d,ids)).join('')}</div></div><div class="section-card" id="roomSelection">${edit?'Tisch antippen, um ihn zu bearbeiten oder Schüler zuzuweisen. Zum Verschieben ziehen.':'Foto oder Namen antippen, um die Schülerkartei zu öffnen.'}</div><p class="sub">Raumplan und Schülerzuordnungen werden im App-Datenbestand gespeichert und bei OneDrive-Synchronisierung übertragen.</p>`;
document.getElementById('roomBack').onclick=()=>{route={type:'class',classId:cid};render()};document.getElementById('roomEdit').onclick=()=>{edit=!edit;selectedId='';renderRoom(cid)};document.getElementById('roomPrint').onclick=()=>window.print();document.getElementById('roomGroup').onchange=e=>{filterGroup=e.target.value;renderRoom(cid)};
if(edit){document.getElementById('roomGrid').onclick=()=>{const r=Math.max(1,Math.min(12,Number(document.getElementById('roomRows').value)||4)),co=Math.max(1,Math.min(10,Number(document.getElementById('roomCols').value)||3));if(!confirm('Tischraster neu erstellen? Bisherige Tischzuordnungen werden dabei gelöscht.'))return;const fresh=createPlan(r,co);fresh.fixtures=p.fixtures;store()[cid]=fresh;save();renderRoom(cid)};for(const type of ['single','double'])document.getElementById(type==='single'?'roomAddSingle':'roomAddDouble').onclick=()=>{p.desks.push({id:uid('desk'),type,x:35,y:42,angle:0,students:[]});save();renderRoom(cid)};document.getElementById('roomAddFixture').onclick=()=>{const type=prompt('Raumelement: Fenster, Tür, Tafel, Lehrertisch oder Wand','window');const aliases={'Fenster':'window','Tür':'door','Tafel':'board','Lehrertisch':'teacher','Wand':'wall'};const t=aliases[type]||type;if(!['window','door','board','teacher','wall'].includes(t))return;p.fixtures.push({id:uid('fixture'),type:t,x:50,y:50,angle:0});save();renderRoom(cid)}}
for(const el of view.querySelectorAll('.room-object')){el.addEventListener('click',e=>{if(el.dataset.dragged==='yes'){el.dataset.dragged='';return}const id=el.dataset.id;if(edit){selectedId=id;renderSelection(cid)}else{const sid=e.target.closest('[data-student]')?.dataset.student;if(sid&&student(sid)){route={type:'student',studentId:sid};render()}}});if(edit)drag(el,p)}
if(edit&&selectedId)renderSelection(cid);
}
function fixtureHTML(f){const names={board:'TAFEL',teacher:'LEHRER',door:'TÜR',window:'FENSTER',wall:'WAND'};return `<div class="room-object room-fixture room-${E(f.type)}" data-id="${E(f.id)}" style="left:${f.x}%;top:${f.y}%;transform:translate(-50%,-50%) rotate(${f.angle}deg)">${names[f.type]||E(f.type)}</div>`}
function deskHTML(d,ids){const count=seats(d),students=(d.students||[]).slice(0,count);return `<div class="room-object room-desk ${d.type==='double'?'room-double':''}" data-id="${E(d.id)}" style="left:${d.x}%;top:${d.y}%;transform:translate(-50%,-50%) rotate(${d.angle}deg)">${Array.from({length:count},(_,i)=>{const s=student(students[i]);return `<div class="room-seat" ${s&&ids.has(s.id)?`data-student="${E(s.id)}"`:''}>${s&&ids.has(s.id)?`${s.photo?`<img src="${E(s.photo)}" alt="">`:''}<span>${label(s)}</span>`:s?'Andere Gruppe':'Platz '+(i+1)}</div>`}).join('')}</div>`}
function drag(el,p){let start=null;el.addEventListener('pointerdown',e=>{if(e.button!==0)return;start={x:e.clientX,y:e.clientY,ox:obj(p,el.dataset.id).x,oy:obj(p,el.dataset.id).y,moved:false};el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!start)return;const canvas=document.getElementById('roomCanvas'),r=canvas.getBoundingClientRect(),o=obj(p,el.dataset.id);if(Math.abs(e.clientX-start.x)+Math.abs(e.clientY-start.y)>5)start.moved=true;if(!start.moved)return;o.x=Math.max(3,Math.min(97,start.ox+(e.clientX-start.x)/r.width*100));o.y=Math.max(3,Math.min(97,start.oy+(e.clientY-start.y)/r.height*100));el.style.left=o.x+'%';el.style.top=o.y+'%'});el.addEventListener('pointerup',()=>{if(start?.moved){el.dataset.dragged='yes';save()}start=null});el.addEventListener('pointercancel',()=>{start=null})}
function renderSelection(cid){const p=plan(cid),o=obj(p,selectedId),box=document.getElementById('roomSelection');if(!o||!box)return;const desk=p.desks.includes(o);const isTeacher=o.type==='teacher';box.innerHTML=`<h3>${desk?'Werkbank':E(o.type)} bearbeiten</h3><div class="toolbar"><button class="btn secondary" id="roomRotate">Drehen +${isTeacher?45:90}°</button>${desk?`<button class="btn secondary" id="roomType">${o.type==='double'?'Zu Einzeltisch':'Zu Doppeltisch'}</button>`:''}<button class="btn danger" id="roomDelete">Entfernen</button></div>${desk?Array.from({length:seats(o)},(_,i)=>`<label>Platz ${i+1}<select data-seat="${i}"><option value="">Nicht zugewiesen</option>${classStudents(cid).map(s=>`<option value="${E(s.id)}" ${(o.students||[])[i]===s.id?'selected':''}>${E(s.name)}</option>`).join('')}</select></label>`).join(''):''}`;box.querySelector('#roomRotate').onclick=()=>{o.angle=(o.angle+(isTeacher?45:90))%360;save();renderRoom(cid)};box.querySelector('#roomDelete').onclick=()=>{p.desks=p.desks.filter(x=>x.id!==o.id);p.fixtures=p.fixtures.filter(x=>x.id!==o.id);selectedId='';save();renderRoom(cid)};if(desk){box.querySelector('#roomType').onclick=()=>{o.type=o.type==='double'?'single':'double';o.students=(o.students||[]).slice(0,seats(o));save();renderRoom(cid)};box.querySelectorAll('[data-seat]').forEach(select=>select.onchange=()=>{const sid=select.value;if(sid){for(const d of p.desks)d.students=(d.students||[]).map(id=>id===sid?'':id)}o.students ||= [];o.students[Number(select.dataset.seat)]=sid;save();renderRoom(cid)})}}
render=function(){if(route.type==='room')renderRoom(route.classId);else{previousRender();if(route.type==='class'){const toolbar=view.querySelector('.view-header .toolbar');if(toolbar){const b=document.createElement('button');b.className='btn secondary';b.textContent='Klassenraumplan';b.onclick=()=>{route={type:'room',classId:route.classId};render()};toolbar.append(b)}}}};
})();
