/* i-i_Doku v7.3 classroom editor: responsive relative geometry, multi-selection, resize, align */
(function(){
'use strict';
const previousRender=render,E=escapeHtml;
const TYPES={board:'Tafel',teacher:'Lehrertisch',door:'Tür',window:'Fenster',wall:'Wand'};
const DEF={single:[14,11],double:[14,16],board:[15,6],teacher:[14,7],door:[9,5],window:[12,5],wall:[20,2]};
let edit=false,activeCid='',selected=new Set(),group='',snap=false,history=[];
const roomGroupByClass={};
function roomKey(cid){return cid+'::'+group}
function copyRoom(src,allowedIds){const p=JSON.parse(JSON.stringify(src));for(const d of p.desks)d.students=(d.students||[]).map(id=>allowedIds.has(id)?id:'');return p}
function groupStudentsForRoom(cid){return classStudents(cid).filter(s=>s.groupId===group)}
function store(){state.roomPlans ||= {};return state.roomPlans}
function make(rows,cols,kind='single'){
 const desks=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)desks.push({id:uid('desk'),type:kind,x:12+(c+.5)*76/cols,y:22+(r+.5)*67/rows,angle:0,students:[],width:Math.min(DEF[kind][0],66/cols),height:Math.min(DEF[kind][1],58/rows)});
 return {rows,cols,desks,fixtures:[{id:uid('f'),type:'board',x:36,y:5,angle:0},{id:uid('f'),type:'teacher',x:79,y:11,angle:0},{id:uid('f'),type:'door',x:6,y:89,angle:0},{id:uid('f'),type:'window',x:94,y:34,angle:90},{id:uid('f'),type:'window',x:94,y:63,angle:90}]};
}
function plan(cid){const s=store(),key=roomKey(cid);if(!s[key]){const base=s[cid]||make(4,3);s[key]=copyRoom(base,new Set(groupStudentsForRoom(cid).map(x=>x.id)));persist()}return s[key]}
function all(p){return [...p.desks,...p.fixtures]}
function get(p,id){return all(p).find(x=>x.id===id)}
function size(o){return [Number(o.width)||DEF[o.type]?.[0]||14,Number(o.height)||DEF[o.type]?.[1]||7]}
function persist(){saveState()}
function checkpoint(p){history.push(JSON.stringify(p));if(history.length>25)history.shift()}
function seats(d){return d.type==='double'?2:1}
function numbering(p,d,i){let n=1;for(const x of p.desks){if(x.id===d.id)return n+i;n+=seats(x)}return n}
function attrs(o){const [w,h]=size(o);return `left:${o.x}%;top:${o.y}%;width:${w}%;height:${h}%;transform:translate(-50%,-50%) rotate(${o.angle||0}deg)`}
function fixtureHTML(o){return `<div class="room-object room-fixture room-${E(o.type)}" data-id="${E(o.id)}" style="${attrs(o)}">${E(TYPES[o.type]||o.type)}</div>`}
function deskHTML(o,p,ids){return `<div class="room-object room-desk ${o.type==='double'?'room-double':''}" data-id="${E(o.id)}" style="${attrs(o)}">${Array.from({length:seats(o)},(_,i)=>{const s=student((o.students||[])[i]);return `<div class="room-seat" ${s&&ids.has(s.id)?`data-student="${E(s.id)}"`:''}>${s&&ids.has(s.id)?`${s.photo?`<img src="${E(s.photo)}" alt="">`:''}<span>${E(s.name)}</span>`:s?'Andere Gruppe':'Platz '+numbering(p,o,i)}</div>`}).join('')}</div>`}
function renderRoom(cid){activeCid=cid;const c=cls(cid);if(!c)return;if(!c.groups?.length){view.innerHTML='<p>Für diese Klasse sind noch keine Gruppen angelegt.</p>';return}if(!c.groups.some(g=>g.id===group))group=roomGroupByClass[cid]||c.groups[0].id;if(!c.groups.some(g=>g.id===group))group=c.groups[0].id;roomGroupByClass[cid]=group;const p=plan(cid),ids=new Set(groupStudentsForRoom(cid).map(s=>s.id));const used=new Set(p.desks.flatMap(d=>d.students||[]).filter(Boolean));
 view.innerHTML=`<div class="view-header"><div><h2>Klassenraumplan · ${E(c.code)} · ${E(c.groups.find(g=>g.id===group)?.name||'')}</h2><div class="sub">${edit?'Bearbeitungsmodus':'Unterrichtsmodus'} · ${p.desks.length} Tische · ${used.size} zugewiesene Schüler</div></div><div class="toolbar"><button class="btn secondary" id="roomBack">Zur Klasse</button><button class="btn" id="roomEdit">${edit?'Unterrichtsmodus':'Bearbeiten'}</button><button class="btn secondary" id="roomPrint">Drucken / PDF</button></div></div>
 <div class="section-card room-tools"><label>Gruppe <select id="roomGroup">${c.groups.map(g=>`<option value="${E(g.id)}" ${group===g.id?'selected':''}>${E(g.name)}</option>`).join('')}</select></label>${edit?`<label>Reihen <input id="roomRows" type="number" min="1" max="12" value="${p.rows}" style="width:65px"></label><label>Spalten <input id="roomCols" type="number" min="1" max="10" value="${p.cols}" style="width:65px"></label><label>Tischtyp <select id="roomKind"><option value="single">Einzeltische</option><option value="double">Doppeltische gegenüber</option></select></label><button class="btn secondary" id="roomGrid">Raster erstellen</button><button class="btn" id="roomSingle">+ Einzeltisch</button><button class="btn" id="roomDouble">+ Doppeltisch</button><label>Element <select id="roomFixture">${Object.entries(TYPES).map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select></label><button class="btn" id="roomAdd">+ Element</button><label><input type="checkbox" id="roomSnap" ${snap?'checked':''}> Rasterfang</label><button class="btn secondary" id="roomCopy">Plan einer anderen Gruppe kopieren</button><button class="btn secondary" id="roomUndo" ${history.length?'':'disabled'}>Rückgängig</button>`:''}</div>
 ${edit?'<div class="sub room-hint">Mehrfachauswahl: Strg + Klick (PC) oder „Mehrfachauswahl“ (Handy). An den Griffen die Größe ändern.</div><label class="room-multi"><input type="checkbox" id="roomMulti"> Mehrfachauswahl (Touch)</label>':''}
 <div class="room-layout"><div class="room-canvas" id="roomCanvas">${p.fixtures.map(fixtureHTML).join('')}${p.desks.map(d=>deskHTML(d,p,ids)).join('')}</div></div><div class="section-card" id="roomSelection">${edit?'Element auswählen oder mehrere Elemente markieren.':'Foto oder Namen antippen, um die Schülerkartei zu öffnen.'}</div><p class="sub">Raumplan und Schülerzuordnungen werden mit dem App-Datenbestand synchronisiert.</p>`;
 document.getElementById('roomBack').onclick=()=>{route={type:'class',classId:cid};render()};document.getElementById('roomEdit').onclick=()=>{edit=!edit;selected.clear();renderRoom(cid)};document.getElementById('roomPrint').onclick=()=>window.print();document.getElementById('roomGroup').onchange=e=>{group=e.target.value;roomGroupByClass[cid]=group;selected.clear();history=[];renderRoom(cid)};
 if(edit){document.getElementById('roomCopy').onclick=()=>{const options=c.groups.filter(g=>g.id!==group);if(!options.length){alert('Keine weitere Gruppe vorhanden.');return}const message='Raumplan kopieren von:\n'+options.map((g,i)=>(i+1)+': '+g.name).join('\n')+'\nBitte Nummer eingeben:';const answer=prompt(message);if(answer===null)return;const source=options[Number(answer)-1];if(!source){alert('Ungültige Gruppenauswahl.');return}if(!confirm('Raumplan von '+source.name+' übernehmen? Die Einrichtung dieser Gruppe wird ersetzt; Schülerzuordnungen werden NICHT übernommen.'))return;const key=roomKey(cid),sourcePlan=store()[cid+'::'+source.id]||store()[cid]||make(4,3);checkpoint(p);store()[key]=copyRoom(sourcePlan,new Set());selected.clear();persist();renderRoom(cid)};document.getElementById('roomSnap').onchange=e=>snap=e.target.checked;document.getElementById('roomUndo').onclick=()=>{if(!history.length)return;store()[roomKey(cid)]=JSON.parse(history.pop());selected.clear();persist();renderRoom(cid)};
 document.getElementById('roomGrid').onclick=()=>{const r=Math.max(1,Math.min(12,+document.getElementById('roomRows').value||4)),co=Math.max(1,Math.min(10,+document.getElementById('roomCols').value||3));if(!confirm('Tischraster ersetzen? Bisherige Tischzuordnungen gehen dabei verloren.'))return;checkpoint(p);const np=make(r,co,document.getElementById('roomKind').value);np.fixtures=p.fixtures;store()[roomKey(cid)]=np;selected.clear();persist();renderRoom(cid)};
 for(const kind of ['single','double'])document.getElementById(kind==='single'?'roomSingle':'roomDouble').onclick=()=>{checkpoint(p);p.desks.push({id:uid('desk'),type:kind,x:50,y:50,angle:0,students:[],width:DEF[kind][0],height:DEF[kind][1]});persist();renderRoom(cid)};
 document.getElementById('roomAdd').onclick=()=>{const type=document.getElementById('roomFixture').value;checkpoint(p);p.fixtures.push({id:uid('fixture'),type,x:50,y:50,angle:0,width:DEF[type][0],height:DEF[type][1]});persist();renderRoom(cid)};
 }
 for(const el of view.querySelectorAll('.room-object')){if(edit){if(selected.has(el.dataset.id))el.classList.add('room-selected');attachDrag(el,p,cid);el.addEventListener('click',e=>{if(el.dataset.dragged==='yes'){el.dataset.dragged='';return}const id=el.dataset.id,multi=e.ctrlKey||e.metaKey||document.getElementById('roomMulti')?.checked;if(!multi)selected.clear();if(multi&&selected.has(id))selected.delete(id);else selected.add(id);refreshSelection(cid)})}else el.addEventListener('click',e=>{const sid=e.target.closest('[data-student]')?.dataset.student;if(sid&&student(sid)){window.__roomReturn={classId:cid,groupId:group,studentId:sid};route={type:'student',studentId:sid};render();const back=document.getElementById('backBtn');if(back)back.onclick=()=>{group=window.__roomReturn.groupId;route={type:'room',classId:window.__roomReturn.classId};render()}}})}
 if(edit&&selected.size)refreshSelection(cid);
}
function refreshSelection(cid){const p=plan(cid),box=document.getElementById('roomSelection');view.querySelectorAll('.room-object').forEach(el=>{el.classList.toggle('room-selected',selected.has(el.dataset.id));el.querySelectorAll('.room-handle').forEach(h=>h.remove());if(edit&&selected.size===1&&selected.has(el.dataset.id)){for(const axis of ['width','height']){const h=document.createElement('span');h.className='room-handle room-handle-'+axis;h.title=axis==='width'?'Breite verändern':'Tiefe verändern';el.append(h);attachResize(h,el,p,cid,axis)}}});
 const os=[...selected].map(id=>get(p,id)).filter(Boolean);if(!os.length){box.textContent='Elemente auswählen: Strg + Klick oder Mehrfachauswahl aktivieren.';return}
 if(os.length>1){box.innerHTML=`<h3>${os.length} Elemente ausgewählt</h3><div class="room-controls"><label>Ausrichten <select id="roomAlign"><option value="left">Links</option><option value="center">Horizontal mittig</option><option value="right">Rechts</option><option value="top">Oben</option><option value="middle">Vertikal mittig</option><option value="bottom">Unten</option></select></label><button class="btn" id="roomAlignGo">Ausrichten</button><button class="btn secondary" id="roomSpaceX">Horizontal verteilen</button><button class="btn secondary" id="roomSpaceY">Vertikal verteilen</button><button class="btn secondary" id="roomSameW">Gleiche Breite</button><button class="btn secondary" id="roomSameH">Gleiche Höhe</button><button class="btn secondary" id="roomSameSize">Gleiche Größe</button><button class="btn danger" id="roomDelete">Auswahl löschen</button></div>`;
 document.getElementById('roomAlignGo').onclick=()=>{checkpoint(p);const k=document.getElementById('roomAlign').value;const edges=os.map(o=>{const [w,h]=size(o);return {o,l:o.x-w/2,r:o.x+w/2,t:o.y-h/2,b:o.y+h/2}});const lo=Math.min(...edges.map(a=>a.l)),hi=Math.max(...edges.map(a=>a.r)),top=Math.min(...edges.map(a=>a.t)),bottom=Math.max(...edges.map(a=>a.b));for(const {o} of edges){const [w,h]=size(o);if(k==='left')o.x=lo+w/2;if(k==='center')o.x=(lo+hi)/2;if(k==='right')o.x=hi-w/2;if(k==='top')o.y=top+h/2;if(k==='middle')o.y=(top+bottom)/2;if(k==='bottom')o.y=bottom-h/2}persist();renderRoom(cid)};
 for(const axis of ['X','Y'])document.getElementById('roomSpace'+axis).onclick=()=>{checkpoint(p);const k=axis==='X'?'x':'y',ordered=[...os].sort((a,b)=>a[k]-b[k]);const min=ordered[0][k],max=ordered[ordered.length-1][k];ordered.forEach((o,i)=>o[k]=min+(max-min)*i/(ordered.length-1));persist();renderRoom(cid)};
 for(const [id,mode] of [['roomSameW','w'],['roomSameH','h'],['roomSameSize','both']])document.getElementById(id).onclick=()=>{checkpoint(p);const [w,h]=size(os[0]);for(const o of os){if(mode!=='h')o.width=w;if(mode!=='w')o.height=h}persist();renderRoom(cid)};
 }else{const o=os[0],desk=p.desks.includes(o),[w,h]=size(o);box.innerHTML=`<h3>${desk?'Werkbank · Platz '+numbering(p,o,0):E(TYPES[o.type]||o.type)} bearbeiten</h3><div class="room-controls"><label>Breite (%) <input id="roomWidth" type="number" min="1" max="90" step="0.5" value="${w}"></label><label>Höhe (%) <input id="roomHeight" type="number" min="1" max="90" step="0.5" value="${h}"></label><label>Drehung <select id="roomAngle">${Array.from({length:8},(_,i)=>`<option value="${i*45}" ${(o.angle||0)===i*45?'selected':''}>${i*45}°</option>`).join('')}</select></label><button class="btn secondary" id="roomApplySize">Größe / Drehung übernehmen</button><button class="btn secondary" id="roomRotate">Drehen +${desk?90:45}°</button>${desk?`<button class="btn secondary" id="roomType">${o.type==='double'?'Einzeltisch':'Doppeltisch'}</button><button class="btn secondary" id="roomSameType">Größe auf alle ${o.type==='double'?'Doppel-':'Einzel-'}tische</button>`:''}<button class="btn danger" id="roomDelete">Entfernen</button></div>${desk?Array.from({length:seats(o)},(_,i)=>`<label>Platz ${numbering(p,o,i)} <select data-seat="${i}"><option value="">Nicht zugewiesen</option>${groupStudentsForRoom(cid).map(s=>`<option value="${E(s.id)}" ${(o.students||[])[i]===s.id?'selected':''}>${E(s.name)}</option>`).join('')}</select></label>`).join(''):''}`;
 document.getElementById('roomApplySize').onclick=()=>{checkpoint(p);o.width=Math.max(1,Math.min(90,+document.getElementById('roomWidth').value||w));o.height=Math.max(1,Math.min(90,+document.getElementById('roomHeight').value||h));o.angle=+document.getElementById('roomAngle').value;persist();renderRoom(cid)};
 document.getElementById('roomRotate').onclick=()=>{checkpoint(p);o.angle=((o.angle||0)+(desk?90:45))%360;persist();renderRoom(cid)};
 if(desk){document.getElementById('roomType').onclick=()=>{checkpoint(p);o.type=o.type==='double'?'single':'double';o.students=(o.students||[]).slice(0,seats(o));persist();renderRoom(cid)};document.getElementById('roomSameType').onclick=()=>{checkpoint(p);for(const d of p.desks.filter(d=>d.type===o.type)){d.width=w;d.height=h}persist();renderRoom(cid)};box.querySelectorAll('[data-seat]').forEach(sel=>sel.onchange=()=>{checkpoint(p);const sid=sel.value;if(sid)for(const d of p.desks)d.students=(d.students||[]).map(x=>x===sid?'':x);o.students ||= [];o.students[+sel.dataset.seat]=sid;persist();renderRoom(cid)})}
 }
 const del=document.getElementById('roomDelete');if(del)del.onclick=()=>{checkpoint(p);p.desks=p.desks.filter(o=>!selected.has(o.id));p.fixtures=p.fixtures.filter(o=>!selected.has(o.id));selected.clear();persist();renderRoom(cid)};
}
function attachDrag(el,p,cid){let start;el.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('.room-handle'))return;const id=el.dataset.id;if(!selected.has(id)&&!(e.ctrlKey||e.metaKey||document.getElementById('roomMulti')?.checked)){selected.clear();selected.add(id)}const os=[...selected].map(id=>get(p,id)).filter(Boolean);start={x:e.clientX,y:e.clientY,orig:os.map(o=>[o,o.x,o.y]),moved:false};el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!start)return;const r=document.getElementById('roomCanvas').getBoundingClientRect(),dx=(e.clientX-start.x)/r.width*100,dy=(e.clientY-start.y)/r.height*100;if(Math.abs(e.clientX-start.x)+Math.abs(e.clientY-start.y)>4)start.moved=true;if(!start.moved)return;for(const [o,x,y] of start.orig){o.x=Math.max(1,Math.min(99,snap?Math.round((x+dx)/2)*2:x+dx));o.y=Math.max(1,Math.min(99,snap?Math.round((y+dy)/2)*2:y+dy));const node=view.querySelector(`.room-object[data-id="${o.id}"]`);if(node){node.style.left=o.x+'%';node.style.top=o.y+'%'}}});el.addEventListener('pointerup',()=>{if(start?.moved){const orig=start.orig.map(([o,x,y])=>[o,x,y]);for(const [o,x,y] of orig){o.x=x;o.y=y}checkpoint(p);for(const [o,x,y] of orig){const r=document.getElementById('roomCanvas').getBoundingClientRect();const dx=(lastX-start.x)/r.width*100,dy=(lastY-start.y)/r.height*100;o.x=Math.max(1,Math.min(99,snap?Math.round((x+dx)/2)*2:x+dx));o.y=Math.max(1,Math.min(99,snap?Math.round((y+dy)/2)*2:y+dy))}persist();el.dataset.dragged='yes'}start=null});let lastX=0,lastY=0;el.addEventListener('pointermove',e=>{lastX=e.clientX;lastY=e.clientY});el.addEventListener('pointercancel',()=>start=null)}
function attachResize(handle,el,p,cid,axis){let start;
 function measure(e){const r=document.getElementById('roomCanvas').getBoundingClientRect(),ang=(start.o.angle||0)*Math.PI/180,dx=(e.clientX-start.x)/r.width*100,dy=(e.clientY-start.y)/r.height*100;const delta=axis==='width'?dx*Math.cos(ang)+dy*Math.sin(ang):-dx*Math.sin(ang)+dy*Math.cos(ang);return Math.max(1,Math.min(90,start.value+delta));}
 handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();const o=get(p,el.dataset.id),[w,h]=size(o);start={x:e.clientX,y:e.clientY,value:axis==='width'?w:h,o};handle.setPointerCapture(e.pointerId)});
 handle.addEventListener('pointermove',e=>{if(!start)return;e.preventDefault();e.stopPropagation();el.style[axis]=measure(e)+'%'});
 handle.addEventListener('pointerup',e=>{if(!start)return;e.preventDefault();e.stopPropagation();const value=measure(e),o=start.o;checkpoint(p);o[axis]=value;start=null;persist();renderRoom(cid)});
 handle.addEventListener('pointercancel',()=>{if(start){start=null;renderRoom(cid)}});
}

render=function(){if(route.type==='room')renderRoom(route.classId);else{previousRender();if(route.type==='class'){const toolbar=view.querySelector('.view-header .toolbar');if(toolbar){const b=document.createElement('button');b.className='btn secondary';b.textContent='Klassenraumplan';b.onclick=()=>{group=roomGroupByClass[route.classId]||'';route={type:'room',classId:route.classId};render()};toolbar.append(b)}}}};
})();
